### ISSUE TITLE
memberByMemberでundefined.mapを呼び出そうとしてエラーになる

### ISSUE THREAD

**Issue by shokai** [stkay/WikipediaNavigator#2]
適当に上下移動し続けていたら、ローディングバーがずっとロード中になりました

![](https://gyazo.com/d7572f7415ae57100a8dc38980718d03/raw)

**Comment by ytanaka-** [comment]
あーこれ自分もなったんですけど、サーバが落ちてるわけではなかったのか

**Comment by isSatake** [comment]
把握してます。誤解を生むUIでスミマセン🙇

**Comment by stkay** [comment]
元データに欠陥があったのが原因だった
